enum TransactionTypeChartOfAccount {
  asset,
  liability,
  equity,
  revenue,
  expense,
}

enum TransactionSubTypeChartOfAccount {
  cash,
  accountReceivable,
  inventory,
  fixedAsset,
  otherAssets,
  accountPayable,
  longTermDebt,
  taxesPayable,
  accruedLiabilities,
  payrollLiabilities,
  otherLiabilities,
  costOfGoodsSold,
  salaryExpenses,
  rentExpenses,
  insuranceExpenses,
  utilityExpenses,
  otherExpenses,
  commonStock,
  retainedEarnings,
  ownerEquity,
  otherEquity,
  salesRevenue,
  serviceRevenue,
  interestRevenue,
  otherRevenue,
}
